version: "3"

services:
  db-postgresql:
    build: ./db
    container_name: modernfarms-db-postgresql
    volumes:
      - ./db/backup/backup.sql:/docker-entrypoint-initdb.d/1-backup.sql
    ports:
      - 5432:5432

  server-rest-golang:
    build: ./server-rest-golang
    image: server-rest-golang:latest
    container_name: modernfarms-server
    ports:
      - 9090:9090
    depends_on: 
      - db-postgresql

  frontend-angular:
    build: ./frontend-angular
    image: frontend-angular:latest
    container_name: modernfarms-frontend
    ports:
      - 4200:80
    depends_on: 
      - server-rest-golang
