version: "3"

services:
  db-postgresql:
    image: modernfarms/harvest_db-postgresql
    container_name: modernfarms-db-postgresql
    volumes:
      - ./db/backup/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/backup/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server-rest-golang:
    image: modernfarms/harvest_server-rest-golang
    container_name: modernfarms-server
    ports:
      - 9090:9090
    depends_on: 
      - db-postgresql

  frontend-angular:
    image: modernfarms/harvest_frontend-angular
    container_name: modernfarms-frontend
    ports:
      - 4200:80
    depends_on: 
      - server-rest-golang
